### ISSUE TITLE
Get Summary from a JIRA ticket when referenced in IRC

### ISSUE THREAD

**Issue by oscerd** [paoloantinori/sopel_modules#1]

**Comment by paoloantinori** [comment]
It shouldn't be that hard:

```
curl -L  https://issues.jboss.org/rest/api/2/issue/ENTESB-6018
```

from https://developer.atlassian.com/jiradev/jira-apis/jira-rest-apis/jira-rest-api-tutorials/jira-rest-api-version-2-tutorial

**Comment by oscerd** [comment]
Great :-)

**Comment by oscerd** [comment]
Done! Thanks @paoloantinori :-)
